### ISSUE TITLE
作者是不是是不是cdn挂了

### ISSUE THREAD

**Issue by wang-xiaowu** [Akilarlxh/hexo-butterfly-clock#1]
作者是不是是不是cdn挂了

**Comment by wang-xiaowu** [comment]
![image](https://user-images.githubusercontent.com/44340137/176092893-c279ad04-f9b9-4397-aa8e-7203c2bf162a.png)

**Comment by Gahotx** [comment]
不是可以自定义配置资源的链接么？自己换了不就好了

**Comment by wang-xiaowu** [comment]
> 不是可以自定义配置资源的链接么？自己换了不就好了

en 我就是问问
